import type { EmployeeAbsence } from '../schedule/types.ts'

export type RequestSystemCode = 'SICK' | 'VACATION' | 'DAY_OFF' | 'SICK_LEAVE' | 'ABSENCE' | 'SHIFT_CHANGE' | 'SHIFT_PROPOSAL' | 'STAFFING' | 'STAFFING_RESPONSE' | 'OTHER'
export type RequestDateMode = 'NONE' | 'SINGLE' | 'RANGE'
export type RequestStatus = 'PENDING' | 'APPROVED' | 'REJECTED' | 'CANCELLED'
export type RequestType = { id: string; name: string; description: string | null; systemCode: RequestSystemCode | null; dateMode: RequestDateMode; requiresComment: boolean; allowsAttachments: boolean; isActive: boolean }
export type StaffRequest = { locationId: string; locationName?: string; timezone?: string; responseCount?: number; staffingRequestId?: string | null; staffingPositionId?: string | null; staffingPositionName?: string | null; absenceReason: 'SICK' | 'PERSONAL' | 'OTHER' | null; id: string; organizationId: string; createdByMemberId: string; requestTypeId: string; typeNameSnapshot: string; systemCodeSnapshot: RequestSystemCode | null; status: RequestStatus; startDate: string | null; endDate: string | null; comment: string | null; relatedShiftId: string | null; originalStartAt: string | null; originalEndAt: string | null; proposedStartAt: string | null; proposedEndAt: string | null; resolvedAt: string | null; resolutionComment: string | null; cancelledAt: string | null; createdAt: string; creatorName: string; creatorRole: 'OWNER' | 'ADMIN' | 'MEMBER'; creatorEmail: string; creatorAvatarUrl: string | null; resolvedByName: string | null; firstReadAt: string | null; readByViewer: boolean; reads: Array<{ memberId: string; readAt: string }>; attachments: Array<{ id: string; fileName: string; mimeType: string; size: number; downloadUrl: string }>; events: Array<{ id: string; type: 'CREATED' | 'APPROVED' | 'REJECTED' | 'CANCELLED'; comment: string | null; createdAt: string; actorName: string }> }
export type RequestList = { requests: StaffRequest[]; pagination: { page: number; pageSize: number; total: number; pages: number }; counters: { pending: number; unread: number } }
export type RequestDetail = { staffingResponses?: StaffRequest[]; viewerResponseId?: string | null; viewerCanRespond?: boolean; absenceConflicts?: Array<{ id: string; type: EmployeeAbsence['type']; startDate: string; endDate: string }>; otherAbsentEmployees?: number; request: StaffRequest; conflicts: Array<{ id: string; scheduledStartAt: string; scheduledEndAt: string }> }
