import { useState, type FormEvent } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { useAuth } from '../../../app/auth/auth-context.tsx'
import { useRequestTypes } from '../../../app/requests/queries.ts'
import type { RequestDateMode, RequestType } from '../../../app/requests/types.ts'
import type { OrganizationSummary } from '../../../app/organizations/types.ts'
import './requests.scss'

const blank = { name: '', description: '', dateMode: 'NONE' as RequestDateMode, requiresComment: false, allowsAttachments: false }

export default function RequestTypesSettings({ organization, onMessage, onError }: { organization: OrganizationSummary; onMessage: (value: string) => void; onError: (value: string) => void }) {
  const { apiRequest } = useAuth()
  const queryClient = useQueryClient()
  const types = useRequestTypes(organization.id, true)
  const [editing, setEditing] = useState<RequestType | null>(null)
  const [form, setForm] = useState(blank)
  const [open, setOpen] = useState(false)
  const [busy, setBusy] = useState(false)
  if (organization.role !== 'OWNER') return null
  const refresh = () => queryClient.invalidateQueries({ queryKey: ['request-types', organization.id] })
  function startEdit(type?: RequestType) { setEditing(type ?? null); setForm(type ? { name: type.name, description: type.description ?? '', dateMode: type.dateMode, requiresComment: type.requiresComment, allowsAttachments: type.allowsAttachments } : blank); setOpen(true) }
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); onError(''); try { const body = { ...form, description: form.description || null, ...(editing ? { isActive: editing.isActive } : {}) }; await apiRequest(`/organizations/${organization.id}/request-types${editing ? `/${editing.id}` : ''}`, { method: editing ? 'PATCH' : 'POST', body }); await refresh(); setOpen(false); onMessage(editing ? 'Тип заявки обновлён.' : 'Тип заявки создан.') } catch (failure) { onError(failure instanceof Error ? failure.message : 'Не удалось сохранить тип заявки.') } finally { setBusy(false) } }
  async function toggle(type: RequestType) { setBusy(true); onError(''); try { await apiRequest(`/organizations/${organization.id}/request-types/${type.id}`, { method: 'PATCH', body: { name: type.name, description: type.description, dateMode: type.dateMode, requiresComment: type.requiresComment, allowsAttachments: type.allowsAttachments, isActive: !type.isActive } }); await refresh(); onMessage(type.isActive ? 'Тип убран из подачи. Старые заявки сохранены.' : 'Тип снова доступен для подачи.') } catch (failure) { onError(failure instanceof Error ? failure.message : 'Не удалось изменить тип заявки.') } finally { setBusy(false) } }
  const system = types.data?.types.filter((type) => type.systemCode) ?? []
  const custom = types.data?.types.filter((type) => !type.systemCode) ?? []
  return <article className="request-types-settings"><header><div><p className="app-eyebrow">Заявки</p><h2>Типы заявок</h2><p>Отключённый тип исчезает из формы подачи. Уже созданные заявки и их история сохраняются.</p></div><button className="app-primary" onClick={() => startEdit()}>+ Создать тип</button></header>{types.isLoading ? <div className="app-state"><span className="app-spinner" /></div> : <><section><h3>Системные</h3>{system.map((type) => <div className={`request-type-row${type.isActive ? '' : ' is-inactive'}`} key={type.id}><div><strong>{type.name}</strong><span>{type.description}</span></div><small>{type.isActive ? 'Доступен' : 'Убран из подачи'}</small><button disabled={busy} onClick={() => void toggle(type)}>{type.isActive ? 'Убрать' : 'Вернуть'}</button></div>)}</section><section><h3>Пользовательские</h3>{custom.length ? custom.map((type) => <div className={`request-type-row${type.isActive ? '' : ' is-inactive'}`} key={type.id}><div><strong>{type.name}</strong><span>{type.description || 'Без описания'}</span></div><small>{type.isActive ? 'Доступен' : 'Убран из подачи'}</small><button onClick={() => startEdit(type)}>Изменить</button><button disabled={busy} onClick={() => void toggle(type)}>{type.isActive ? 'Убрать' : 'Вернуть'}</button></div>) : <p className="request-types-empty">Пользовательских типов пока нет.</p>}</section></>}{open && <div className="request-type-form"><form onSubmit={submit}><header><h3>{editing ? 'Изменить тип' : 'Новый тип заявки'}</h3><button type="button" onClick={() => setOpen(false)}>×</button></header><label><span>Название</span><input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} minLength={2} maxLength={100} required /></label><label><span>Описание</span><textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} maxLength={500} rows={3} /></label><label><span>Тип даты</span><select value={form.dateMode} onChange={(event) => setForm({ ...form, dateMode: event.target.value as RequestDateMode })}><option value="NONE">Не требуется</option><option value="SINGLE">Одна дата</option><option value="RANGE">Период</option></select></label><label className="request-type-check"><input type="checkbox" checked={form.requiresComment} onChange={(event) => setForm({ ...form, requiresComment: event.target.checked })} /><span>Требовать комментарий</span></label><label className="request-type-check"><input type="checkbox" checked={form.allowsAttachments} onChange={(event) => setForm({ ...form, allowsAttachments: event.target.checked })} /><span>Разрешить вложения</span></label><footer><button type="button" className="app-secondary" onClick={() => setOpen(false)}>Отмена</button><button className="app-primary" disabled={busy}>{busy ? 'Сохраняем…' : 'Сохранить'}</button></footer></form></div>}</article>
}
