import DocumentActionsMenu from './document-actions-menu.tsx'
import { useToast } from '../../../component/ui/toast/toast-context.ts'
import { useEffect, useRef, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { useMutation } from '@tanstack/react-query'
import { useAuth } from '../../../app/auth/auth-context.tsx'
import type { OrganizationSummary } from '../../../app/organizations/types.ts'
import { useDocumentRefresh, useDocuments, useDocumentMembers } from '../../../app/documents/queries.ts'
import type { DocumentItem, Folder } from '../../../app/documents/types.ts'
import { documentPath, visibilityLabels } from '../../../app/documents/types.ts'
import Avatar from '../../../component/ui/avatar/avatar.tsx'
import Select from '../../../component/ui/select/select.tsx'
import AnimatedOverlay from '../schedule/animated-overlay.tsx'
import DocumentRow from './document-row.tsx'
import DocumentDrawer from './document-drawer.tsx'
import DocumentDialog from './document-dialog.tsx'
import { AssignmentForm, DocumentForm, FolderForm } from './document-forms.tsx'
import './documents.scss'

type Dialog = { type: 'upload' } | { type: 'revision'; item: DocumentItem } | { type: 'edit'; item: DocumentItem } | { type: 'assign'; item: DocumentItem } | { type: 'delete'; item: DocumentItem } | { type: 'folder'; item?: Folder } | { type: 'deleteFolder'; item: Folder }
export default function DocumentsPage({ organization }: { organization: OrganizationSummary }) {
  const toast = useToast()
  const [forwardFolders, setForwardFolders] = useState<string[]>([])
  const [dialogBusy, setDialogBusy] = useState(false)
  const manager = organization.role !== 'MEMBER', { apiRequest } = useAuth(), refresh = useDocumentRefresh()
  const [params, setParams] = useSearchParams(), [scope, setScope] = useState(params.get('member') ? 'personal' : params.get('section') ?? 'workspace'), [search, setSearch] = useState(''), [debounced, setDebounced] = useState(''), [visibility, setVisibility] = useState(''), [fileType, setFileType] = useState(''), [sort, setSort] = useState('updated'), [highlight, setHighlight] = useState(''), [page, setPage] = useState(1), [dialog, setDialog] = useState<Dialog | null>(null)
  const folderId = params.get('folder') ?? '', targetMemberId = params.get('member') ?? '', documentId = params.get('document') ?? ''
  const documents = useDocuments(organization.id, { scope, search: debounced, folderId: folderId || undefined, visibility: visibility || undefined, fileType: fileType || undefined, sort, targetMemberId: targetMemberId || undefined, page })
  const members = useDocumentMembers(organization.id, manager && scope === 'personal')
  const selectedMember = members.data?.members.find(member => member.id === targetMemberId)
  const required = useDocuments(organization.id, { scope: 'required', pageSize: 5 })
  useEffect(() => { const timer = window.setTimeout(() => { setDebounced(search.trim()); setPage(1) }, 250); return () => window.clearTimeout(timer) }, [search])
  const sectionParam = params.get('section')
  useEffect(() => { setScope(targetMemberId ? 'personal' : ['personal', 'mine', 'acknowledgements', 'control', 'history'].includes(sectionParam ?? '') ? sectionParam! : 'workspace') }, [sectionParam, targetMemberId])
  const folders = documents.data?.folders ?? [], current = folders.find(folder => folder.id === folderId)
  const breadcrumbs: Folder[] = []; let parent = current; const seen = new Set<string>(); while (parent && !seen.has(parent.id)) { breadcrumbs.unshift(parent); seen.add(parent.id); parent = folders.find(folder => folder.id === parent?.parentId) }
  const savedScroll = useRef(0), folderScroll = useRef(new Map<string, number>())
  function setParam(key: string, value: string) { if (key === 'document' && value) savedScroll.current = window.scrollY; if (key === 'folder') { folderScroll.current.set(folderId, window.scrollY); requestAnimationFrame(() => window.scrollTo({ top: folderScroll.current.get(value) ?? 0 })) }; setParams(previous => { const next = new URLSearchParams(previous); if (value) next.set(key, value); else next.delete(key); return next }); if (key !== 'document') setPage(1); else if (!value) requestAnimationFrame(() => window.scrollTo({ top: savedScroll.current })); }
  function navigateFolder(id: string) { setForwardFolders([]); setParam('folder', id) }
  const pin = useMutation({ mutationFn: (folder: Folder) => apiRequest(`/organizations/${organization.id}/document-folders/${folder.id}/pin`, { method: folder.pinned ? 'DELETE' : 'PUT' }), onSuccess: async (_result, folder) => { await refresh(); toast(folder.pinned ? 'Папка откреплена.' : 'Папка закреплена.') } })
  const deletion = useMutation({ mutationFn: (value: Dialog) => value.type === 'delete' ? apiRequest(documentPath(organization.id, value.item.id), { method: 'DELETE' }) : value.type === 'deleteFolder' ? apiRequest(`/organizations/${organization.id}/document-folders/${value.item.id}`, { method: 'DELETE' }) : Promise.resolve(), onSuccess: async () => { setDialog(null); setParam('document', ''); await refresh(); toast('Удалено. История документов сохранена.') } })
  function changeScope(value: string) { setForwardFolders([]); setScope(value); setPage(1); setVisibility(''); setFileType(''); setParams(previous => { const next = new URLSearchParams(previous); next.delete('folder'); if (value !== 'personal') next.delete('member'); if (value !== 'workspace') next.set('section', value); else next.delete('section'); return next }) }
  const childFolders = scope === 'workspace' && !debounced && !visibility && !fileType ? folders.filter(folder => folder.parentId === (folderId || null)).sort((a, b) => Number(b.pinned) - Number(a.pinned) || a.name.localeCompare(b.name, 'ru')) : []
  const filtered = Boolean(debounced || visibility || fileType)
  function resetFilters() { setSearch(''); setDebounced(''); setVisibility(''); setFileType(''); setPage(1) }
  function folderPath(id: string | null) {
    const names: string[] = []; const visited = new Set<string>(); let cursor = folders.find(folder => folder.id === id)
    while (cursor && !visited.has(cursor.id)) { visited.add(cursor.id); names.unshift(cursor.name); cursor = folders.find(folder => folder.id === cursor?.parentId) }
    return ['Библиотека', ...names].join(' / ')
  }
  async function saved(id?: string) { if (id) { setPage(1); setHighlight(id); window.setTimeout(() => setHighlight(previous => previous === id ? '' : previous), 4500) }; await refresh() }
  return <section className="documents-page"><header className="documents-heading"><div><h1>Документы</h1><p>Библиотека организации и ознакомления.</p></div>{manager && (!current || current.canManage) && scope !== 'mine' && <div className="documents-heading__actions">{scope === 'workspace' && <button className="app-secondary" onClick={() => setDialog({ type: 'folder' })}>Создать папку</button>}<button className="app-primary" onClick={() => setDialog({ type: 'upload' })}>Загрузить документ</button></div>}</header>

    <nav className="account-settings-tabs" aria-label="Разделы документов"><button className={scope === 'workspace' ? 'active' : ''} onClick={() => changeScope('workspace')}>{manager ? 'Библиотека' : 'Документы организации'}</button>{manager && <button className={scope === 'control' ? 'active' : ''} onClick={() => changeScope('control')}>Ознакомление</button>}{manager && <button className={scope === 'personal' ? 'active' : ''} onClick={() => changeScope('personal')}>Документы сотрудников</button>}<button className={scope === 'mine' ? 'active' : ''} onClick={() => changeScope('mine')}>Мои документы</button>{!manager && <button className={scope === 'acknowledgements' ? 'active' : ''} onClick={() => changeScope('acknowledgements')}>Требуют ознакомления{required.data?.pagination.total ? ` · ${required.data.pagination.total}` : ''}</button>}</nav>
    <div className="members-toolbar document-toolbar"><label><span className="document-sr-only">Поиск документов</span><input type="search" maxLength={160} placeholder={scope === 'workspace' ? 'Поиск по всей библиотеке' : 'Поиск документов'} value={search} onChange={event => setSearch(event.target.value)} /></label>{manager && scope === 'personal' && <MemberFilter organizationId={organization.id} value={targetMemberId} onChange={value => setParam('member', value)} />}<label><span className="document-sr-only">Сортировка</span><Select value={sort} onChange={event => { setSort(event.target.value); setPage(1) }}><option value="updated">По обновлению</option><option value="name">По названию</option><option value="created">Сначала новые</option></Select></label></div>
    <div className="document-filters" id="document-filters">{manager && !['personal', 'mine'].includes(scope) && <label><span>Кто видит документ</span><Select value={visibility} onChange={event => { setVisibility(event.target.value); setPage(1) }}><option value="">Любой доступ</option>{Object.entries(visibilityLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</Select></label>}<label><span>Формат</span><Select value={fileType} onChange={event => { setFileType(event.target.value); setPage(1) }}><option value="">Все форматы</option><option value="pdf">PDF</option><option value="office">Office</option><option value="image">Изображения</option><option value="text">TXT и CSV</option></Select></label></div>
    {filtered && <div className="document-filter-chips">{debounced && <span>Поиск: {debounced}</span>}{visibility && <span>{visibilityLabels[visibility as keyof typeof visibilityLabels]}</span>}{fileType && <span>{{ pdf: 'PDF', office: 'Office', image: 'Изображения', text: 'TXT и CSV' }[fileType]}</span>}<button onClick={resetFilters}>Сбросить фильтры</button></div>}
    {scope === 'personal' && selectedMember && <div className="document-employee-heading"><Avatar className="app-avatar" url={selectedMember.avatarUrl} name={selectedMember.name} /><div><strong>{selectedMember.name}</strong><small>{selectedMember.email}{selectedMember.former ? ' · бывший сотрудник' : ''}{documents.data && !filtered ? ` · документов: ${documents.data.pagination.total}` : ''}</small></div></div>}
    <div className="document-list-heading">{scope === 'workspace' ? <nav className="document-breadcrumbs" aria-label="Расположение папки">{folderId && <button className="document-folder-nav" aria-label="На уровень выше" onClick={() => { setForwardFolders(previous => [folderId, ...previous]); setParam('folder', current?.parentId ?? '') }}>← Назад</button>}{forwardFolders.length > 0 && <button className="document-folder-nav" aria-label="Вперёд по папкам" onClick={() => { const [next, ...rest] = forwardFolders; setParam('folder', next); setForwardFolders(rest) }}>Вперёд →</button>}<button aria-current={!folderId ? 'page' : undefined} onClick={() => navigateFolder('')}>Библиотека</button>{!debounced && breadcrumbs.map(folder => <span key={folder.id}>/<button aria-current={folder.id === folderId ? 'page' : undefined} onClick={() => navigateFolder(folder.id)}>{folder.name}</button></span>)}</nav> : <h2>{scope === 'history' ? 'Журнал удалений' : scope === 'control' ? 'Контроль ознакомлений команды' : scope === 'acknowledgements' ? 'Ваши ознакомления' : scope === 'mine' ? 'Мои документы' : targetMemberId ? 'Личные документы выбранного сотрудника' : 'Личные документы всех сотрудников'}</h2>}{manager && <button className="document-history-link" onClick={() => changeScope(scope === 'history' ? 'workspace' : 'history')}>{scope === 'history' ? 'Вернуться в библиотеку' : 'Журнал удалений'}</button>}</div>
    {folderId && !current && scope === 'workspace' && !documents.isLoading && <p className="app-alert">Папка недоступна или удалена. Вернитесь в библиотеку.</p>}
    <div className="document-list"><div className="document-list-columns" aria-hidden="true"><span>Документ</span><span>Доступ</span><span>Ознакомление</span><span>Обновлён</span><span /></div>
      {childFolders.map(folder => <article className="document-folder-row" key={folder.id}><button className="document-folder-open" onClick={() => navigateFolder(folder.id)}><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" aria-hidden="true"><path d="M3 6h7l2 2h9v12H3V6Z" /></svg><span><strong>{folder.pinned && <span className="document-folder-pin" aria-label="Закреплена">★ </span>}{folder.name}</strong><small>Документов: {folder.documentCount}</small></span></button><DocumentActionsMenu label={`Действия с папкой ${folder.name}`}><button disabled={pin.isPending} onClick={() => pin.mutate(folder)}>{folder.pinned ? 'Открепить папку' : 'Закрепить папку'}</button>{manager && folder.canManage && <><button onClick={() => setDialog({ type: 'folder', item: folder })}>Изменить папку</button><button onClick={() => { deletion.reset(); setDialog({ type: 'deleteFolder', item: folder }) }}>Удалить</button></>}</DocumentActionsMenu></article>)}
      {documents.isLoading ? <div className="app-state"><span className="app-spinner" />Загружаем документы…</div> : documents.isError ? <div className="app-state" role="alert"><p>{documents.error.message}</p><button className="app-secondary" onClick={() => void documents.refetch()}>Повторить</button></div> : documents.data?.documents.length ? documents.data.documents.map(item => <DocumentRow key={item.id} item={item} acknowledgementHighlight={scope === 'acknowledgements'} columns highlighted={item.id === highlight} path={debounced ? folderPath(item.folderId) : undefined} onOpen={() => setParam('document', item.id)} onEdit={manager && item.canManage && !item.deletedAt ? () => setDialog({ type: 'edit', item }) : undefined} onAssign={manager && item.canManage && !item.deletedAt ? () => setDialog({ type: 'assign', item }) : undefined} onDelete={manager && item.canManage && !item.deletedAt ? () => { deletion.reset(); setDialog({ type: 'delete', item }) } : undefined} />) : <div className="app-state"><p>{filtered ? 'Документы не найдены.' : scope === 'control' ? 'Все назначенные ознакомления завершены.' : scope === 'acknowledgements' ? 'Документов для ознакомления пока нет.' : scope === 'history' ? 'Удалённых документов нет.' : scope === 'mine' ? 'Личных документов пока нет.' : scope === 'personal' ? targetMemberId ? `У ${selectedMember?.name ?? 'выбранного сотрудника'} пока нет документов.` : 'Документов сотрудников пока нет.' : folderId ? 'В этой папке пока нет документов.' : childFolders.length ? 'В этом разделе нет файлов. Откройте папку или загрузите документ.' : 'Добавьте первый документ.'}</p>{filtered ? <button className="app-secondary" onClick={resetFilters}>Сбросить фильтры</button> : manager && ['workspace', 'personal'].includes(scope) && <button className="app-secondary" onClick={() => setDialog({ type: 'upload' })}>{folderId ? 'Загрузить в эту папку' : 'Загрузить документ'}</button>}</div>}
    </div>
    {documents.data && documents.data.pagination.pages > 1 && <div className="document-pagination"><button className="app-secondary" disabled={page === 1} onClick={() => setPage(page - 1)}>Назад</button><span>{page}/{documents.data.pagination.pages} · {documents.data.pagination.total} документов</span><button className="app-secondary" disabled={page === documents.data.pagination.pages} onClick={() => setPage(page + 1)}>Далее</button></div>}
    {documentId && !dialog && <AnimatedOverlay variant="modal" className="document-viewer-overlay" onClose={() => setParam('document', '')}>{close => <DocumentDrawer key={documentId} organizationId={organization.id} documentId={documentId} manager={manager} folders={folders} onClose={close} onRevision={item => setDialog({ type: 'revision', item })} onEdit={item => setDialog({ type: 'edit', item })} onAssign={item => setDialog({ type: 'assign', item })} onDelete={item => { deletion.reset(); setDialog({ type: 'delete', item }) }} />}</AnimatedOverlay>}
    {dialog && <AnimatedOverlay variant="modal" dismissible={!deletion.isPending && !dialogBusy} onClose={() => setDialog(null)}>{close => dialog.type === 'upload' || dialog.type === 'edit' || dialog.type === 'revision' ? <DocumentForm organizationId={organization.id} folders={folders} folderId={folderId} targetMemberId={targetMemberId || undefined} item={dialog.type === 'edit' ? dialog.item : undefined} revision={dialog.type === 'revision' ? dialog.item : undefined} onClose={close} onSaved={saved} personal={scope === 'personal'} uploadMaxBytes={documents.data?.uploadMaxBytes} onBusy={setDialogBusy} /> : dialog.type === 'assign' ? <AssignmentForm item={dialog.item} onClose={close} onSaved={refresh} onBusy={setDialogBusy} /> : dialog.type === 'folder' ? <FolderForm organizationId={organization.id} folders={folders} parentId={folderId} item={dialog.item} onClose={close} onSaved={refresh} onBusy={setDialogBusy} /> : <DocumentDialog title={dialog.type === 'delete' ? 'Удалить документ?' : 'Удалить папку?'} onClose={close}><p>{dialog.type === 'delete' ? `«${dialog.item.displayName}» будет скрыт. Незавершённые требования отменятся, история сохранится.` : `Удалить папку «${dialog.item.name}»? Папка должна быть пустой.`}</p>{deletion.error && <p className="form-inline-error" role="alert">{deletion.error.message}</p>}<footer><button className="app-secondary" disabled={deletion.isPending} onClick={close}>Назад</button><button className="app-primary" disabled={deletion.isPending} onClick={() => deletion.mutate(dialog)}>{deletion.isPending ? 'Удаляем…' : 'Удалить'}</button></footer></DocumentDialog>}</AnimatedOverlay>}
  </section>
}
function MemberFilter({ organizationId, value, onChange }: { organizationId: string; value: string; onChange: (value: string) => void }) {
  const members = useDocumentMembers(organizationId)
  return <label className="document-member-filter"><span className="document-sr-only">Сотрудник</span><Select searchable value={value} onChange={event => onChange(event.target.value)}><option value="">Все сотрудники</option>{members.data?.members.map(member => <option key={member.id} value={member.id} data-search={`${member.name} ${member.email}`}><span className="staffly-select__person"><Avatar className="app-avatar document-avatar" url={member.avatarUrl} name={member.name} /><span>{member.name}<small>{member.email}{member.former ? ' · бывший сотрудник' : ''}</small></span></span></option>)}</Select></label>
}
