import { z } from 'zod'
const uuid = z.uuid()
export const paramsSchema = z.object({ organizationId: uuid, documentId: uuid.optional(), folderId: uuid.optional(), acknowledgementId: uuid.optional() })
export const metadataSchema = z.object({ pointId: uuid.nullable().optional(), shared: z.boolean().optional(), displayName: z.string().trim().min(1).max(255), folderId: uuid.nullable().default(null), visibility: z.enum(['ORGANIZATION', 'ADMINS', 'PRIVATE_MEMBER']), targetMemberId: uuid.nullable().default(null) }).strict().refine(value => (value.visibility === 'PRIVATE_MEMBER') === Boolean(value.targetMemberId), { message: 'Для личного документа выберите сотрудника; для остальных получатель не нужен.' })
export const listSchema = z.object({ pointId: z.union([uuid, z.literal('shared'), z.literal('all')]).optional(), search: z.string().trim().max(160).default(''), folderId: uuid.optional(), visibility: z.enum(['ORGANIZATION', 'ADMINS', 'PRIVATE_MEMBER']).optional(), targetMemberId: uuid.optional(), fileType: z.enum(['pdf', 'office', 'image', 'text']).optional(), sort: z.enum(['updated', 'name', 'created']).default('updated'), scope: z.enum(['workspace', 'control', 'required', 'acknowledgements', 'personal', 'mine', 'history']).default('workspace'), page: z.coerce.number().int().min(1).max(100000).default(1), pageSize: z.coerce.number().int().min(1).max(100).default(25) })
export const folderSchema = z.object({ pointId: uuid.nullable().optional(), visibility: z.enum(['ORGANIZATION', 'ADMINS']).default('ORGANIZATION'), shared: z.boolean().optional(), name: z.string().trim().min(1).max(160), parentId: uuid.nullable().default(null) }).strict()
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(value => !Number.isNaN(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value, 'Некорректная дата')
export const assignSchema = z.object({ recipients: z.enum(['all', 'roles', 'members']), roles: z.array(z.enum(['OWNER', 'ADMIN', 'MEMBER'])).max(3).default([]), memberIds: z.array(uuid).max(1000).default([]), deadline: date.nullable().default(null), comment: z.string().trim().max(1000).nullable().default(null) }).strict().refine(value => value.recipients === 'all' || (value.recipients === 'roles' ? value.roles.length > 0 : value.memberIds.length > 0), 'Выберите получателей')
export type Metadata = z.infer<typeof metadataSchema>
export type ListOptions = z.infer<typeof listSchema>
export type Assignment = z.infer<typeof assignSchema>
